name: docs
channels:

  - conda-forge
  - pytorch
  - defaults
  - pyg

dependencies:

  # Base depends
  - python >=3.8,<=3.10
  - pip

  # Core dependencies
  - numpy<2
  - pandas
  - pytorch
  - pydantic<2 # workaround to avoid clashes with lightning
  - lightning

  # utils
  - matplotlib
  - nbsphinx
  - ipython
  - ipykernel
  - scikit-learn
  - scipy
  - torch-scatter

  # Pip-only installs
  - pip:
    - sphinx-copybutton
    - furo
    - KDEpy
