name: CI

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # The cookiecutter uses the "--initial-branch" flag when it runs git-init
  push:
    branches:
      - "release/2.0"
  pull_request:
    branches:
      - "release/2.0"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 2 * * 1"

jobs:
  plumed_interfaces:
    name: Test plumed interfaces
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package
        run: |
          python -m pip install -e .[test]

      - name: Configure libtorch flags
        # we take the flags to point to the libtorch shipped with pytorch
        run: |
          PIP_CPPFLAGS=$(python libtorch_flags_from_python.py --cppflags)
          PIP_LDFLAGS=$(python libtorch_flags_from_python.py --ldflags)

          echo "LDFLAGS=$PIP_LDFLAGS $LDFLAGS" >> $GITHUB_ENV
          echo "CPPFLAGS=$PIP_CPPFLAGS $CPPFLAGS" >> $GITHUB_ENV
      
      - name: Get plumed
        run: |
          PLUMED_VER="2.10.0"
          echo "PLUMED_VER=$PLUMED_VER" >> $GITHUB_ENV
          wget https://github.com/plumed/plumed2/releases/download/v$PLUMED_VER/plumed-src-$PLUMED_VER.tgz
          tar -xzf plumed-src-$PLUMED_VER.tgz
        
      - name: Configure and make plumed
        run: |
          echo "pwd : $PWD"
          echo "LDFLAGS : $LDFLAGS"
          echo "CPPFLAGS : $CPPFLAGS"
          echo "plumed version : $PLUMED_VER"
          cd plumed-$PLUMED_VER
          echo "pwd after cd: $PWD"
          echo "files in directory: $(ls)"

          mkdir build
          ./configure --prefix=$PWD/build --enable-libtorch
          make -j 8
          make -j 8 install 
      
      - name: Create sourceme.sh plumed
        run: |
          echo "pwd : $PWD"
          cd plumed-$PLUMED_VER
          echo "pwd after cd: $PWD"
          echo "files in directory: $(ls)"

          PLUMED_DIR=$PWD
          echo """export PLUMED_DIR=$PLUMED_DIR

          export PATH="$PLUMED_DIR/build/bin/:$PATH"
          export LIBRARY_PATH="$PLUMED_DIR/build/lib/:$LIBRARY_PATH"
          export LD_LIBRARY_PATH="$PLUMED_DIR/build/lib/:$LD_LIBRARY_PATH"
          export PLUMED_KERNEL="$PLUMED_DIR/build/lib/libplumedKernel.so"
          export PLUMED_VIMPATH="$PLUMED_DIR/vim"
          export PYTHONPATH="$PLUMED_DIR/python:$PYTHONPATH"
          export PKG_CONFIG_PATH="$PLUMED_DIR/build/lib/pkgconfig:$PKG_CONFIG_PATH"
          """ >> sourceme.sh

          head sourceme.sh -n 20

          source sourceme.sh

          echo $(which plumed)
      - name: Check installation
        run: |
          echo "pwd : $PWD"
          cd plumed-$PLUMED_VER
          echo "pwd after cd: $PWD"
          echo "files in directory: $(ls)"

          source sourceme.sh
          
          plumed --version
          plumed config has libtorch
          plumed config module pytorch

      - name: Test plumed interfaces
        run: |
          echo "Here we have to do some tests folks :D"
